version: '3.8'

services:
  # ตู้เก็บข้อมูล (Database)
  db:
    image: postgres:15
    container_name: airbnb_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: airbnb_raw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # หน้าจอสำหรับส่องข้อมูล (Database Management Tool)
  pgadmin:
    image: dpage/pgadmin4
    container_name: airbnb_pgadmin
    user: root  # เพิ่มอันนี้เพื่อให้มีสิทธิ์เขียนไฟล์ลงเครื่องหนูได้
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  
    depends_on:
      - db