version: '3.8'

services:
  # Database Service: Primary Data Store
  db:
    image: postgres:15
    container_name: airbnb_db
    restart: always  
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: airbnb_raw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airbnb_network

  # GUI Tool: Database Administration
  pgadmin:
    image: dpage/pgadmin4
    container_name: airbnb_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_CONFIG_SERVER_MODE: 'False' 
    ports:
      - "8080:80"
    volumes:
      - pgadmin_storage:/var/lib/pgadmin  .
    depends_on:
      - db
    networks:
      - airbnb_network

networks:
  airbnb_network:  
    driver: bridge

volumes:
  pgadmin_storage: